version: '3.8'

services:
  api:
    build: .
    container_name: taskmanager-api
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagerDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "11433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
